services:
  db-1:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data-1 
 
  db-2:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data-2
 
  db-3:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data-d
    

 
 
volumes:
  pgdata: