services:
  db-1:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./.data/pgdata-1:/var/lib/postgresql/data-1 
      - ./docker-entrypoint-initdb.d/db1/:/docker-entrypoint-initdb.d/
 
  db-2:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5433:5432"
    volumes:
      - ./.data/pgdata-2:/var/lib/postgresql/data-2
      - ./docker-entrypoint-initdb.d/db2/:/docker-entrypoint-initdb.d/
 
  db-3:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5434:5432"
    volumes:
      - ./.data/pgdata-3:/var/lib/postgresql/data-3
      - ./docker-entrypoint-initdb.d/db3/:/docker-entrypoint-initdb.d/
     
 
volumes:
  pgdata-1:
  pgdata-2:
  pgdata-3: